# Common functions shared between the scripts in this directory
#
# Copyright (c) 2025, Monocot Limited. All rights reserved
#
# This source code is subject to the terms of the BSD 2 Clause License. If the BSD 2 Clause License
# was not distributed with this source code in the LICENSE file, you can obtain it at
# https://opensource.org/license/bsd-2-clause

import numpy as np
import os
import sys
import tomllib

from collections import namedtuple
from math import *
from scipy.interpolate import pchip_interpolate

DEFAULT_SSIMU2_LO = 30
DEFAULT_SSIMU2_HI = 90
DEFAULT_SSIMU2_STEP = 1

# Note: Speed settings are called "speed" if higher numbers are faster,
# and "effort" if higher numbers are slower
DEFAULT_SETTINGS = {
  "aom": {"speed": "6", "tune": None},
  "svt": {"speed": "6", "tune": None},
  "rav1e": {"speed": "6"},
  "tinyavif": {},
  "jpegxl": {"effort": "7"},
  "jpegli": {},
  "webp": {"effort": "4"},
}
ENCODERS = set(DEFAULT_SETTINGS.keys())

FORMATS = {
  "yuv8", # 8-bit Y4M, bt.709 colour space (TODO: Add support for other colour spaces)
  "yuv10", # 10-bit Y4M, bt.709 colour space
  "yuv12", # 12-bit Y4M, bt.709 colour space
  "png8", # 8-bit PNG, sRGB colour space
  "png16", # 8-bit PNG, sRGB colour space
}

# Kate Morley's 12-bit rainbow: 12 colours of similar saturation and lightness
# Source: https://iamkate.com/data/12-bit-rainbow/
# This list is rotated by one entry, to place the reddest shade first,
# as that's more pleasing to me.
CURVE_COLOURS = ["#a35", "#c66", "#e94", "#ed0", "#9d5", "#4d8",
                 "#2cb", "#0bc", "#09c", "#36b", "#639", "#817"]

# Different curve styles used when comparing multiple source lists
# (eg. for 8 vs. 10 bit encoding)
# Use a solid line, then a dashed line, then a dotted line
CURVE_STYLES = ["-", "--", ":"]

CACHE_TAG="""Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag generated by the Monocot image encoder comparison scripts
# For information about cache directory tags, see:
#       http://www.brynosaurus.com/cachedir/
"""

Source = namedtuple("Source", ["tag", "path"])
Encoder = namedtuple("Encoder", ["tag", "encoder", "format", "settings"])
EncodeData = namedtuple("EncodeData", ["size", "runtime", "ssimu2", "fullres_ssimu2"])

def print_error(message):
  print(f"Error: {message}", file=sys.stderr)

def center_text(text, length):
  assert length >= len(text)
  left_padding = (length - len(text)) // 2
  right_padding = (length - len(text) + 1) // 2
  result = " " * left_padding + text + " " * right_padding
  assert len(result) == length
  return result

# Flatten a list of lists (or a generator of lists) into a single list
def flatten(list_of_lists):
  result = []
  for l in list_of_lists:
    result.extend(l)
  return result

def add_cache_tag(cachedir):
  cache_tag_path = os.path.join(cachedir, "CACHEDIR.TAG")
  if not os.path.exists(cache_tag_path):
    open(cache_tag_path, "w").write(CACHE_TAG)

def load_source_list(source_list_path):
  sources = []

  # Treat all entries in this list file as paths relative to the list itself
  source_list_basename = os.path.basename(source_list_path)
  source_list_dir = os.path.dirname(source_list_path)

  data = tomllib.load(open(source_list_path, "rb"))

  for tag, params in data["sources"].items():
    # Allow sources to be specified as `tag = path` if no other settings are needed
    if isinstance(params, str):
      path = params
      params = {}
    else:
      path = params["path"]

    # Normalize parameters
    full_path = os.path.abspath(os.path.join(source_list_dir, path))

    # Check that the provided parameters make sense
    if not os.path.exists(full_path):
      print_error(f"{source_list_path}: {tag}: Input file {full_path} does not exist")
      sys.exit(1)

    sources.append(Source(tag, full_path))

  return sources

def load_encoder_list(encoder_list_path):
  encoders = []

  # Treat all entries in this list file as paths relative to the list itself
  encoder_list_basename = os.path.basename(encoder_list_path)
  encoder_list_dir = os.path.dirname(encoder_list_path)

  data = tomllib.load(open(encoder_list_path, "rb"))

  for tag, params in data["encoders"].items():
    # Check that the provided parameters make sense
    if "encoder" not in params:
      print_error(f"{encoder_list_path}: {tag}: No encoder specified")
      sys.exit(1)

    encoder = params["encoder"]

    if encoder not in ENCODERS:
      print_error(f"{encoder_list_path}: {tag}: Unknown encoder {encoder}")
      sys.exit(1)

    if "format" not in params:
      print_error(f"{encoder_list_path}: {tag}: No input format specified")
      sys.exit(1)

    format_ = params["format"]

    if params["format"] not in FORMATS:
      print_error(f"{encoder_list_path}: {tag}: Unknown input format {format_}")
      sys.exit(1)

    # Assume any other parameters are per-encoder settings
    settings = DEFAULT_SETTINGS[encoder].copy()
    for key, value in params.items():
      if key == "encoder" or key == "format":
        # Skip these two
        continue

      if key not in DEFAULT_SETTINGS[encoder]:
        print_error(f"{encoder_list_path}: {tag}: Unknown setting {key} for encoder {encoder}")
        sys.exit(1)

      settings[key] = value

    encoders.append(Encoder(tag, encoder, format_, settings))

  return encoders

def calculate_target_ssimu2_points(range, step):
  if range is None:
    lo = DEFAULT_SSIMU2_LO
    hi = DEFAULT_SSIMU2_HI
  else:
    try:
      (lo, hi) = range.split("-")
      lo = float(lo)
      hi = float(hi)
    except:
      print_error(f"Invalid SSIMU2 range {range}")
      sys.exit(2)

  num_steps = int((hi - lo) // step) + 1
  target_ssimu2_points = np.linspace(lo, hi, num_steps)

  return target_ssimu2_points

def interpolate_curves(db, encoder, source, target_ssimu2_points):
  curves = []

  resolutions = db.execute("SELECT resolution_index, width, height FROM sources WHERE source = :source;",
                           {"source": source.tag}).fetchall()
  resolutions.sort()
  num_resolutions = len(resolutions)

  fullres_width = resolutions[0][1]
  fullres_height = resolutions[0][2]
  fullres_num_pixels = fullres_width * fullres_height

  num_target_ssimu2_points = len(target_ssimu2_points)
  multires_log_bpp = np.full(num_target_ssimu2_points, np.inf)
  multires_log_nspp = np.full(num_target_ssimu2_points, np.inf)

  min_target_ssimu2 = min(target_ssimu2_points)
  max_target_ssimu2 = max(target_ssimu2_points)

  for (resolution_index, width, height) in resolutions:
    num_pixels = width * height

    query = db.execute("SELECT size, runtime, ssimu2, fullres_ssimu2 FROM results "
                       "WHERE encoder = :encoder AND source = :source AND resolution_index = :resolution_index;",
                       {"encoder": encoder.tag, "source": source.tag, "resolution_index": resolution_index})

    # Map result rows to a proper object
    query.row_factory = lambda _, row: EncodeData._make(row)
    results = query.fetchall()

    num_points = len(results)
    if num_points == 0:
      print_error(f"No encodes found for encoder {encoder}, source {source}")
      sys.exit(1)

    results.sort(key = lambda row: row.ssimu2) # Sort in ascending order of SSIMU2 scores

    # TODO: Filter to keep only points on the convex hull
    min_ssimu2 = results[0].ssimu2
    max_ssimu2 = results[-1].ssimu2
    if min_ssimu2 > min_target_ssimu2 or max_ssimu2 < max_target_ssimu2:
      print_error(f"SSIMU2 scores for (encoder={encoder.tag}, source={source.tag}) don't cover a wide enough range")
      print_error(f"SSIMU2 range covered is [{min_ssimu2:.1f}, {max_ssimu2:.1f}] vs. expected [{min_target_ssimu2:.1f}, {max_target_ssimu2:.1f}]")
      sys.exit(1)

    # Split results and map to log-space for interpolation
    # (which will make it easier to take geometric means later)
    # Also convert from absolute size (in bytes) and runtime (in seconds)
    # to bits/pixel and ns/pixel respectively
    sameres_log_bpp_points = np.zeros(num_points)
    sameres_log_nspp_points = np.zeros(num_points)
    sameres_ssimu2_points = np.zeros(num_points)
    for row_index, row in enumerate(results):
      sameres_log_bpp_points[row_index] = log(row.size * 8.0 / num_pixels)
      sameres_log_nspp_points[row_index] = log(row.runtime * 1000000000.0 / num_pixels)
      sameres_ssimu2_points[row_index] = row.ssimu2

    # Output same-res curve...
    sameres_log_bpp = pchip_interpolate(sameres_ssimu2_points, sameres_log_bpp_points, target_ssimu2_points)
    sameres_log_nspp = pchip_interpolate(sameres_ssimu2_points, sameres_log_nspp_points, target_ssimu2_points)
    curves.append((resolution_index, sameres_log_bpp, sameres_log_nspp))



    # Re-sort for fullres curve generation
    results.sort(key = lambda row: row.fullres_ssimu2)

    fullres_log_bpp_points = np.zeros(num_points)
    fullres_log_nspp_points = np.zeros(num_points)
    fullres_ssimu2_points = np.zeros(num_points)
    for row_index, row in enumerate(results):
      fullres_log_bpp_points[row_index] = log(row.size * 8.0 / fullres_num_pixels)
      fullres_log_nspp_points[row_index] = log(row.runtime * 1000000000.0 / fullres_num_pixels)
      fullres_ssimu2_points[row_index] = row.fullres_ssimu2

    # For the full-res curve (which gets merged into the multires curve), we might not necessarily
    # have enough data to cover the full target SSIMU2 range. This is okay, we just need to filter
    # the curve so that we have appropriate data
    min_fullres_ssimu2 = results[0].fullres_ssimu2
    max_fullres_ssimu2 = results[-1].fullres_ssimu2

    fullres_target_ssimu2_points = []
    fullres_index_map = []
    for index, target_ssimu2 in enumerate(target_ssimu2_points):
      if min_fullres_ssimu2 <= target_ssimu2 <= max_fullres_ssimu2:
        fullres_target_ssimu2_points.append(target_ssimu2)
        fullres_index_map.append(index)

    # ...and merge fullres curve into multires curve
    fullres_log_bpp = pchip_interpolate(fullres_ssimu2_points, fullres_log_bpp_points, fullres_target_ssimu2_points)
    fullres_log_nspp = pchip_interpolate(fullres_ssimu2_points, fullres_log_nspp_points, fullres_target_ssimu2_points)
    for i in range(len(fullres_target_ssimu2_points)):
      if fullres_log_bpp[i] < multires_log_bpp[fullres_index_map[i]]:
        multires_log_bpp[fullres_index_map[i]] = fullres_log_bpp[i]
        multires_log_nspp[fullres_index_map[i]] = fullres_log_nspp[i]

  # Output multires curve
  # First check that we got data for all points. This should always be the case, because the first
  # resolution point should be the full resolution, and therefore should cover the full SSIMU2 range
  # in order to generate that same-res graph properly. So if we didn't get data for all points here,
  # that's a bug in the logic
  assert np.max(multires_log_bpp) < np.inf
  assert np.max(multires_log_nspp) < np.inf
  curves.append((num_resolutions, multires_log_bpp, multires_log_nspp))

  return curves
