[sources]
aspen = "../test-videos/NTIA 422/aspen_1080p_f0_420.y4m"
controlled_burn = "../test-videos/NTIA 422/controlled_burn_1080p_f0_420.y4m"
red_kayak = "../test-videos/NTIA 422/red_kayak_1080p_f0_420.y4m"
rush_field_cuts = "../test-videos/NTIA 422/rush_field_cuts_1080p_f0_420.y4m"
touchdown_pass = "../test-videos/NTIA 422/touchdown_pass_1080p_f0_420.y4m"
crowd_run = "../test-videos/SVT/crowd_run_1080p50_f0_420.y4m"
ducks_take_off = "../test-videos/SVT/ducks_take_off_1080p50_f0_420.y4m"
in_to_tree = "../test-videos/SVT/in_to_tree_1080p50_f0_420.y4m"
old_town_cross = "../test-videos/SVT/old_town_cross_1080p50_f0_420.y4m"
park_joy = "../test-videos/SVT/park_joy_1080p50_f0_420.y4m"
blue_sky = "../test-videos/TMT 420/blue_sky_1080p25_f0_420.y4m"
pedestrian_area = "../test-videos/TMT 420/pedestrian_area_1080p25_f0_420.y4m"
riverbed = "../test-videos/TMT 420/riverbed_1080p25_f0_420.y4m"
station2 = "../test-videos/TMT 420/station2_1080p25_f0_420.y4m"
sunflower = "../test-videos/TMT 420/sunflower_1080p25_f0_420.y4m"
tractor = "../test-videos/TMT 420/tractor_1080p25_f0_420.y4m"

# Excluded files - handled either too well (minimum ssimu2 > 30) or too badly (maximum ssimu2 < 90)
# by at least one encoder
#speed_bag = "../test-videos/NTIA 422/speed_bag_1080p_f0_420.y4m"
#west_wind_easy = "../test-videos/NTIA 422/west_wind_easy_1080p_f0_420.y4m"
#rush_hour = "../test-videos/TMT 420/rush_hour_1080p25_f0_420.y4m"
